project_style:
  content_structure:  'simple_book'
  should_register:    false
  get_druid_from:     'container'
  use_druid_minter:   false

bundle_dir:           '/thumpers/dpgthumper-staging/ArchivesParlementaires'
staging_dir:          '/dor/assembly'

manifest:             ~
checksums_file:       ~
desc_md_template:     ~

progress_log_file:    'log/progress_ap.yaml'
project_name:         'ArchivesParlementaires'
apo_druid_id:         'druid:hy787xj5878'
set_druid_id:         ~

publish_attr:
  publish:            'no'
  shelve:             'no'
  preserve:           'yes'

compute_checksum:     true
init_assembly_wf:     true

content_md_creation:
  style:              :default
  pre_md_file:        ~

object_discovery:
  use_manifest:       false
  glob:               '*'
  regex:              '^[a-z][a-z]\d\d\d[a-z][a-z]\d\d\d\d$'

stageable_discovery:
  use_container:      false
  glob:               '00/*'
  regex:              ~

manifest_cols:
  object_container:   ~
  source_id:          ~
  label:              ~

content_exclusion:    ~

validate_usage:       true
show_progress:        true
limit_n:              ~
uniqify_source_ids:   false
cleanup:              false
resume:               false
