project_style:
  content_structure:  simple_image
  should_register:    false
  get_druid_from:     container

bundle_dir:           spec/test_data/bundle_input_b
staging_dir:          tmp

manifest:             ~
checksums_file:       ~
desc_md_template:     ~

project_name:         Revs
apo_druid_id:         druid:qv648vd4392
set_druid_id:         ~

publish_attr:
  publish:            no
  shelve:             no
  preserve:           yes

init_assembly_wf:     false

object_discovery:
  use_manifest:       false
  glob:               '*'
  regex:              '^[a-z][a-z]\d\d\d[a-z][a-z]\d\d\d\d$'

stageable_discovery:
  use_container:      false
  glob:               '*'
  regex:              '(?ix) ^ ( \d+\.tif | descMetadata\.xml ) $'

manifest_cols:
  object_container:   ~
  source_id:          ~
  label:              ~

content_exclusion:    '(?ix) descMetadata\.xml $'

validate_usage:       true
show_progress:        true
limit_n:              10
uniqify_source_ids:   true
cleanup:              true
