bundle_dir:           spec/test_data/bundle_input_c
staging_dir:          tmp

manifest:             manifest.csv
checksums_file:       checksums.txt
descriptive_metadata_template: mods_template.xml

project_name:         ReidDennis
apo_druid_id:         druid:qv648vd4392
set_druid_id:         ~

publish:              no
shelve:               no
preserve:             yes

limit_n:              1
uniqify_source_ids:   true
show_progress:        true
validate_usage:       true

init_assembly_wf:     true

project_style:        style_revs

object_discovery:
  use_manifest:       true
  glob:               ~
  regex:              ~

stageable_discovery:
  use_container:      true
  glob:               ~
  regex:              ~

manifest_cols:
  object_container:   file_name
  source_id:          stanford_file_id
  label:              title1

content_exclusion:    ~
