:bundle_dir:           spec/test_data/bundle_input_b
:staging_dir:          tmp

:manifest:             manifest.csv
:checksums_file:       checksums.txt
:descriptive_metadata_template: mods_template.xml

:project_name:         Revs
:apo_druid_id:         druid:qv648vd4392
:set_druid_id:         druid:yt502zj0924

:publish:              no
:shelve:               no
:preserve:             yes

:cleanup:              false
:limit_n:              10
:uniqify_source_ids:   true
:show_progress:        false
:validate_usage:       true

:project_style:        style_rumsey
