
:bundle_dir:           'spec/test_data/bundle_input'
:staging_dir:          'tmp'





:manifest:             'manifest.csv'
:checksums_file:       'checksums.txt'
:project_name:         'REVS'
:apo_druid_id:         'druid:qv648vd4392'
:set_druid_id:         'druid:nt028fd5773'

:publish:              'no'
:shelve:               'no'
:preserve:             'yes'                        

:cleanup:              true
:limit_n:              10
:uniquify_source_ids:  true
:show_progress:        true
