:bundle_dir:           spec/test_data/bundle_input_a
:staging_dir:          tmp

:manifest:             manifest.csv
:checksums_file:       checksums.txt

:project_name:         Revs
:apo_druid_id:         druid:qv648vd4392
:set_druid_id:         druid:yt502zj0924

:publish:              no
:shelve:               no
:preserve:             yes                        

:cleanup:              true
:limit_n:              10
:uniqify_source_ids:   true
:show_progress:        false

:pre_assembly_steps:
  :generate_manifest:            false
  :generate_provider_checksums:  false
  :acquire_druid_using:          registration
  :add_dor_object_to_set:        true
  :stage_files:                  true
  :create_content_metadata:      true
  :create_desc_metadata:         true
  :initialize_assembly_workflow: true
