project_style:
  content_structure:  'simple_image'
  should_register:    true
  get_druid_from:     'suri'
  use_druid_minter:   false

bundle_dir:           '/thumpers/dpgthumper2-se1/ReidDennis/tiffs'
staging_dir:          '/dor/assembly'

manifest:             'manifest.csv'
checksums_file:       ~
desc_md_template:     'mods_template.xml'

progress_log_file:    'log/progress_reid_dennis.yaml'
project_name:         'ReidDennis'
apo_druid_id:         'druid:sd064kn5856'
set_druid_id:         ~

publish_attr:
  publish:            'no'
  shelve:             'no'
  preserve:           'yes'

compute_checksum:     true
init_assembly_wf:     true

content_md_creation:
  style:              :default
  pre_md_file:        ~

object_discovery:
  use_manifest:       true
  glob:               ~
  regex:              ~

stageable_discovery:
  use_container:      true
  glob:               ~
  regex:              ~

manifest_cols:
  object_container:   'file_name'
  source_id:          'stanford_file_id'
  label:              'title1'

content_exclusion:    ~

validate_usage:       true
show_progress:        true
limit_n:              ~
uniqify_source_ids:   false
cleanup:              false
