:bundle_dir:           '/home/lyberadmin/pre-assembly/integration_input'
# :bundle_dir:           '/thumpers/dpgthumper-staging/Revs/source/2012_02_22'
:staging_dir:          '/dor/assembly_test'
:manifest:             'manifest.csv'
:checksums_file:       'checksums.txt'
:project_name:         'REVS'
:apo_druid_id:         'druid:qv648vd4392'
:collection_druid_id:  'druid:nt028fd5773'

:cleanup:              true
:limit_n:              10
