bundle_dir:           /home/lyberadmin/pre-assembly/revs_test_run/input
staging_dir:          /home/lyberadmin/pre-assembly/revs_test_run/output

manifest:             manifest.csv
checksums_file:       checksums.txt
desc_meta_template:   mods_template.xml

project_name:         Revs
apo_druid_id:         druid:qv648vd4392
set_druid_id:         druid:yt502zj0924

publish_attr:
  publish:            no
  shelve:             no
  preserve:           yes

limit_n:              10
uniqify_source_ids:   false
cleanup:              false
show_progress:        true
validate_usage:       true

init_assembly_wf:     true

project_style:        style_revs

object_discovery:
  use_manifest:       true
  glob:               ~
  regex:              ~

stageable_discovery:
  use_container:      true
  glob:               ~
  regex:              ~

manifest_cols:
  object_container:   filename
  source_id:          sourceid
  label:              label

content_exclusion:    ~
