# For temporary use on sul-lyberservices-dev.
:bundle_dir:           '/home/lyberadmin/pre-assembly/revs_test_run/input'
:staging_dir:          '/home/lyberadmin/pre-assembly/revs_test_run/output'

# Old tempoary values on lyberservices-dev.
# :bundle_dir:           '/thumpers/dpgthumper-staging/Revs/source/2012_02_22'
# :staging_dir:          '/dor/assembly_test'

:manifest:             'manifest.csv'
:checksums_file:       'checksums.txt'
:project_name:         'REVS'
:apo_druid_id:         'druid:qv648vd4392'
:set_druid_id:         'druid:nt028fd5773'

:publish:              'no'
:shelve:               'no'
:preserve:             'yes'                        

:cleanup:              false
:limit_n:              10
:uniquify_source_ids:  false
:show_progress:        true
