:bundle_dir:           'spec/test_data/bundle_input'
:manifest:             'manifest.csv'
:checksums_file:       'checksums.txt'
:project_name:         'REVS'
:apo_druid_id:         'druid:qv648vd4392'
:collection_druid_id:  'druid:nt028fd5773'
:staging_dir:          'tmp'

# TODO: revs.yaml: set to false in real usage.
:cleanup:              true
