inherit_from: .rubocop_todo.yml
require: rubocop-rspec

# rspec expect{...} is conventional
Layout/SpaceBeforeBlockBraces:
  Exclude:
    - 'spec/**/*_spec.rb'

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 200
