language: ruby

sudo: false
notifications:
  email: false

addons:
  apt:
    packages:
      - libimage-exiftool-perl

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

cache: bundler
services:
- postgresql

before_script:
- bundle exec rake travis_setup_postgres db:reset

rvm:
  - 2.4.4
